name: renderable
description: Testing features for Jinja.dart.
version: 1.0.0-dev+127
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: ^1.8.0
  string_scanner: ^1.1.0
  textwrap: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  stack_trace: ^1.10.0
  test: ^1.17.5
