name: dart-code-metrics-action

on:
  push:
    branches:
      - master

jobs:
  check:
    name: dart-code-metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: dart-code-metrics
        uses: dart-code-checker/dart-code-metrics-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
